tasks:
  - name: my-shell
    before: |
      cd /workspace/gitpod-jupyter
      python -m pip install --upgrade pip
      pip install -r requirements.txt 2>&1 > install.log
    command: |
      cd /workspace/gitpod-jupyter
      echo -e "\n\n\t\t** Starting notebook ... **\n\n"
      ./start_jupyter.sh
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
ports:
  - port: 8888
    onOpen: ignore
    visibility: public
