tasks:
  - name: bash
    command: |
      cd /workspace/workshop-ai-as-api
      echo -e "\n\n\t\t** READY TO START... **\n\n"
      gp open README.md
  - name: api-shell
    before: |
      cd /workspace/gitpod-jupyter
      python -m pip install --upgrade pip
      pip install -r requirements.txt 2>&1 > install.log
    command: |
      cd /workspace/gitpod-jupyter/notebook
      echo -e "\n\n\t\t** PLACEHOLDER **\n\n"
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
ports:
  - port: 8888
    onOpen: ignore
    visibility: public
